exp_name: siglip2_heat
save_dir: /media/data1/feihong/ckpt/ground_siglip2_heat

model:
  type: siglip2_heat
  use_angle: true
  use_heatmap: true
  use_text: false

train:
  batch_size: 48

eval:
  output_dir: eval_results/grounding/siglip2_heat
