exp_name: model_wo_angle_wo_text
save_root: /media/data1/feihong/ckpt
end_num: 0.5
use_ap: true

config:
  NUM_EPOCHS: 16
  BATCH_SIZE: 16
  GRAD_ACCUMULATION_STEPS: 2
  LEARNING_RATE: 5.0e-5
  USE_AMP: true
  ENABLE_TF32: true
  ENCODER_TYPE: heat
  OPTIMIZE_OBJECTIVE: combined
  USE_ANGLE_INPUT: false
  USE_TEXT_INPUT: false
  USE_HEATMAP_LOSS: true
  HEATMAP_LOSS_WEIGHT: 0.2
  HEATMAP_CONFIDENCE_WEIGHT: 0.5
